service: mal-proxy

provider:
  name: aws
  runtime: nodejs6.10


stage: dev
region: us-east-1

functions:

  searchMal:
    handler: src/searchHandler.search
    events:
      - http:
          path: search
          method: get
  
  verifyCredentials:
    handler: src/verifyCredentialshandler.verifyCredentials
    events:
      - http:
          path: verify
          method: get
  
  addToMal:
    handler: src/addHandler.add
    events:
      - http:
          path: add
          method: post
  
  updateOnMal:
    handler: src/updateHandler.update
    events:
      - http:
          path: update
          method: put
  
  deleteFromMal:
    handler: src/deleteHandler.delete
    events:
      - http:
          path: delete
          method: post