service: mal-proxy

provider:
  name: aws
  runtime: nodejs6.10


stage: dev
region: us-east-1

functions:
  malProxy:
    handler: handler.malProxy
    events:
      - http:
          path:   malProxy
          method: get
